services:
  php:
    image: php:8.3-apache
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasktrail-php
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tasktrail.rule=Host(`tasktrail.test`)"
      - "traefik.http.services.tasktrail.loadbalancer.server.port=80"
      - "traefik.http.routers.tasktrail.entrypoints=websecure"
      - "traefik.http.routers.tasktrail.tls.certresolver=myresolver"
    networks:
      - app-network
      - traefik-network

  mysql:
    image: mysql:8.0
    container_name: tasktrail-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tasktraildb
      MYSQL_USER: tasktraildbuser
      MYSQL_PASSWORD: tasktraildbpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: tasktrail-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: tasktrail-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
  traefik-network:
    external: true
